// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { GetApiIdentityMeData, GetApiIdentityMeResponses, PostApiIdentityLoginData, PostApiIdentityLoginResponses, PostApiIdentityLogoutData, PostApiIdentityLogoutResponses, PostApiIdentityRefreshData, PostApiIdentityRefreshResponses, PostApiIdentityRegisterData, PostApiIdentityRegisterResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiIdentityMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiIdentityMeData, ThrowOnError>): RequestResult<GetApiIdentityMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiIdentityMeResponses, unknown, ThrowOnError>({ url: '/api/identity/me', ...options });

export const postApiIdentityRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiIdentityRegisterData, ThrowOnError>): RequestResult<PostApiIdentityRegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiIdentityRegisterResponses, unknown, ThrowOnError>({
    url: '/api/identity/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiIdentityLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiIdentityLoginData, ThrowOnError>): RequestResult<PostApiIdentityLoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiIdentityLoginResponses, unknown, ThrowOnError>({
    url: '/api/identity/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiIdentityRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostApiIdentityRefreshData, ThrowOnError>): RequestResult<PostApiIdentityRefreshResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiIdentityRefreshResponses, unknown, ThrowOnError>({ url: '/api/identity/refresh', ...options });

export const postApiIdentityLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiIdentityLogoutData, ThrowOnError>): RequestResult<PostApiIdentityLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiIdentityLogoutResponses, unknown, ThrowOnError>({ url: '/api/identity/logout', ...options });
