// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:60583/' | (string & {});
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    accessToken: string;
    expiresAtUtc: string;
};

export type RefreshResponse = {
    accessToken: string;
    expiresAtUtc: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    displayName: string;
};

export type RegisterResponse = {
    userId: string;
    email: string;
    displayName: string;
};

export type GetApiIdentityMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/me';
};

export type GetApiIdentityMeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiIdentityMeResponse = GetApiIdentityMeResponses[keyof GetApiIdentityMeResponses];

export type PostApiIdentityRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/identity/register';
};

export type PostApiIdentityRegisterResponses = {
    /**
     * Created
     */
    201: RegisterResponse;
};

export type PostApiIdentityRegisterResponse = PostApiIdentityRegisterResponses[keyof PostApiIdentityRegisterResponses];

export type PostApiIdentityLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/identity/login';
};

export type PostApiIdentityLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiIdentityLoginResponse = PostApiIdentityLoginResponses[keyof PostApiIdentityLoginResponses];

export type PostApiIdentityRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/refresh';
};

export type PostApiIdentityRefreshResponses = {
    /**
     * OK
     */
    200: RefreshResponse;
};

export type PostApiIdentityRefreshResponse = PostApiIdentityRefreshResponses[keyof PostApiIdentityRefreshResponses];

export type PostApiIdentityLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/logout';
};

export type PostApiIdentityLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiIdentityLogoutResponse = PostApiIdentityLogoutResponses[keyof PostApiIdentityLogoutResponses];
