// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import { client } from './client.gen.js';
import type { GetApiReportingDashboardData, GetApiReportingDashboardResponses, GetApiReportingNetWorthHistoryData, GetApiReportingNetWorthHistoryResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiReportingDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetApiReportingDashboardData, ThrowOnError>): RequestResult<GetApiReportingDashboardResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiReportingDashboardResponses, unknown, ThrowOnError>({ url: '/api/reporting/dashboard', ...options });

export const getApiReportingNetWorthHistory = <ThrowOnError extends boolean = false>(options?: Options<GetApiReportingNetWorthHistoryData, ThrowOnError>): RequestResult<GetApiReportingNetWorthHistoryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiReportingNetWorthHistoryResponses, unknown, ThrowOnError>({ url: '/api/reporting/net-worth-history', ...options });
