// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import { client } from './client.gen.js';
import type { GetApiMarketdataInstrumentsByIdData, GetApiMarketdataInstrumentsByIdResponses, GetApiMarketdataInstrumentsSearchData, GetApiMarketdataInstrumentsSearchResponses, GetApiMarketdataSyncStatusData, GetApiMarketdataSyncStatusResponses, PostApiMarketdataFxLatestBatchData, PostApiMarketdataFxLatestBatchResponses, PostApiMarketdataInstrumentsData, PostApiMarketdataInstrumentsResponses, PostApiMarketdataPricesLatestBatchData, PostApiMarketdataPricesLatestBatchResponses, PostApiMarketdataSyncTriggerData, PostApiMarketdataSyncTriggerResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiMarketdataInstrumentsSearch = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataInstrumentsSearchData, ThrowOnError>): RequestResult<GetApiMarketdataInstrumentsSearchResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataInstrumentsSearchResponses, unknown, ThrowOnError>({ url: '/api/marketdata/instruments/search', ...options });

export const postApiMarketdataInstruments = <ThrowOnError extends boolean = false>(options: Options<PostApiMarketdataInstrumentsData, ThrowOnError>): RequestResult<PostApiMarketdataInstrumentsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiMarketdataInstrumentsResponses, unknown, ThrowOnError>({
    url: '/api/marketdata/instruments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiMarketdataInstrumentsById = <ThrowOnError extends boolean = false>(options: Options<GetApiMarketdataInstrumentsByIdData, ThrowOnError>): RequestResult<GetApiMarketdataInstrumentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiMarketdataInstrumentsByIdResponses, unknown, ThrowOnError>({ url: '/api/marketdata/instruments/{id}', ...options });

export const postApiMarketdataPricesLatestBatch = <ThrowOnError extends boolean = false>(options: Options<PostApiMarketdataPricesLatestBatchData, ThrowOnError>): RequestResult<PostApiMarketdataPricesLatestBatchResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiMarketdataPricesLatestBatchResponses, unknown, ThrowOnError>({
    url: '/api/marketdata/prices/latest-batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiMarketdataFxLatestBatch = <ThrowOnError extends boolean = false>(options: Options<PostApiMarketdataFxLatestBatchData, ThrowOnError>): RequestResult<PostApiMarketdataFxLatestBatchResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiMarketdataFxLatestBatchResponses, unknown, ThrowOnError>({
    url: '/api/marketdata/fx/latest-batch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiMarketdataSyncTrigger = <ThrowOnError extends boolean = false>(options?: Options<PostApiMarketdataSyncTriggerData, ThrowOnError>): RequestResult<PostApiMarketdataSyncTriggerResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiMarketdataSyncTriggerResponses, unknown, ThrowOnError>({ url: '/api/marketdata/sync/trigger', ...options });

export const getApiMarketdataSyncStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataSyncStatusData, ThrowOnError>): RequestResult<GetApiMarketdataSyncStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataSyncStatusResponses, unknown, ThrowOnError>({ url: '/api/marketdata/sync/status', ...options });
