// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { GetApiMarketdataBondSeriesByCodeData, GetApiMarketdataBondSeriesByCodeResponses, GetApiMarketdataBondSeriesData, GetApiMarketdataBondSeriesResponses, GetApiMarketdataInstrumentsByIdData, GetApiMarketdataInstrumentsByIdResponses, GetApiMarketdataInstrumentsSearchData, GetApiMarketdataInstrumentsSearchResponses, GetApiMarketdataMetalPricesData, GetApiMarketdataMetalPricesResponses, GetApiMarketdataSyncStatusData, GetApiMarketdataSyncStatusResponses, PostApiMarketdataInstrumentsData, PostApiMarketdataInstrumentsResponses, PostApiMarketdataSyncTriggerData, PostApiMarketdataSyncTriggerResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getApiMarketdataInstrumentsSearch = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataInstrumentsSearchData, ThrowOnError>): RequestResult<GetApiMarketdataInstrumentsSearchResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataInstrumentsSearchResponses, unknown, ThrowOnError>({ url: '/api/marketdata/instruments/search', ...options });

export const postApiMarketdataInstruments = <ThrowOnError extends boolean = false>(options: Options<PostApiMarketdataInstrumentsData, ThrowOnError>): RequestResult<PostApiMarketdataInstrumentsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiMarketdataInstrumentsResponses, unknown, ThrowOnError>({
    url: '/api/marketdata/instruments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiMarketdataInstrumentsById = <ThrowOnError extends boolean = false>(options: Options<GetApiMarketdataInstrumentsByIdData, ThrowOnError>): RequestResult<GetApiMarketdataInstrumentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiMarketdataInstrumentsByIdResponses, unknown, ThrowOnError>({ url: '/api/marketdata/instruments/{id}', ...options });

export const postApiMarketdataSyncTrigger = <ThrowOnError extends boolean = false>(options?: Options<PostApiMarketdataSyncTriggerData, ThrowOnError>): RequestResult<PostApiMarketdataSyncTriggerResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiMarketdataSyncTriggerResponses, unknown, ThrowOnError>({ url: '/api/marketdata/sync/trigger', ...options });

export const getApiMarketdataSyncStatus = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataSyncStatusData, ThrowOnError>): RequestResult<GetApiMarketdataSyncStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataSyncStatusResponses, unknown, ThrowOnError>({ url: '/api/marketdata/sync/status', ...options });

export const getApiMarketdataBondSeries = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataBondSeriesData, ThrowOnError>): RequestResult<GetApiMarketdataBondSeriesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataBondSeriesResponses, unknown, ThrowOnError>({ url: '/api/marketdata/bond-series', ...options });

export const getApiMarketdataBondSeriesByCode = <ThrowOnError extends boolean = false>(options: Options<GetApiMarketdataBondSeriesByCodeData, ThrowOnError>): RequestResult<GetApiMarketdataBondSeriesByCodeResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetApiMarketdataBondSeriesByCodeResponses, unknown, ThrowOnError>({ url: '/api/marketdata/bond-series/{code}', ...options });

export const getApiMarketdataMetalPrices = <ThrowOnError extends boolean = false>(options?: Options<GetApiMarketdataMetalPricesData, ThrowOnError>): RequestResult<GetApiMarketdataMetalPricesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiMarketdataMetalPricesResponses, unknown, ThrowOnError>({ url: '/api/marketdata/metal-prices', ...options });
