// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddCustomInstrumentRequest = {
    ticker: string;
    name: string;
    quoteCurrency: string;
    assetClass: AssetClass;
    allowUnverified?: boolean;
};

export type AssetClass = number;

export type BondSeriesListItem = {
    code: string;
    type: TreasuryBondType;
    isin: string;
    saleStart: string;
    saleEnd: string;
    issuePrice: number | string;
    swapPrice: null | number | string;
    marginPercent: null | number | string;
    firstPeriodRatePercent: null | number | string;
};

export type BondSeriesPeriodRateResponse = {
    periodIndex: number | string;
    ratePercent: number | string;
};

export type BondSeriesResponse = {
    code: string;
    type: TreasuryBondType;
    isin: string;
    saleStart: string;
    saleEnd: string;
    issuePrice: number | string;
    swapPrice: null | number | string;
    marginPercent: null | number | string;
    periodRates: Array<BondSeriesPeriodRateResponse>;
};

export type CustomInstrumentResponse = {
    id: string;
    ticker: string;
    name: string;
    source: PriceSource;
    quoteCurrency: string;
    assetClass: AssetClass;
    verificationStatus: InstrumentVerificationStatus;
};

export type InstrumentDetailsResponse = {
    id: string;
    ticker: string;
    name: string;
    assetClass: AssetClass;
    quoteCurrency: string;
    source: PriceSource;
    verificationStatus: InstrumentVerificationStatus;
    lastPrice: null | number | string;
    lastPriceDate: null | string;
};

export type InstrumentSearchResult = {
    id: string;
    ticker: string;
    name: string;
    assetClass: AssetClass;
    quoteCurrency: string;
    verificationStatus: InstrumentVerificationStatus;
    lastPrice: null | number | string;
    lastPriceDate: null | string;
};

export type InstrumentVerificationStatus = number;

export type PriceSource = number;

export type SyncRunStatus = number;

export type SyncRunSummary = {
    runId: string;
    status: SyncRunStatus;
    startedAt: string;
    finishedAt?: null | string;
    syncedCount: number | string;
    noDataCount: number | string;
    failedCount: number | string;
};

export type SyncStatusResponse = {
    hasRun: boolean;
    prices?: null | SyncRunSummary;
    fx?: null | SyncRunSummary;
    backfill?: null | SyncRunSummary;
};

export type TreasuryBondType = number;

export type GetApiMarketdataInstrumentsSearchData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        limit?: number | string;
    };
    url: '/api/marketdata/instruments/search';
};

export type GetApiMarketdataInstrumentsSearchResponses = {
    /**
     * OK
     */
    200: Array<InstrumentSearchResult>;
};

export type GetApiMarketdataInstrumentsSearchResponse = GetApiMarketdataInstrumentsSearchResponses[keyof GetApiMarketdataInstrumentsSearchResponses];

export type PostApiMarketdataInstrumentsData = {
    body: AddCustomInstrumentRequest;
    path?: never;
    query?: never;
    url: '/api/marketdata/instruments';
};

export type PostApiMarketdataInstrumentsResponses = {
    /**
     * Created
     */
    201: CustomInstrumentResponse;
};

export type PostApiMarketdataInstrumentsResponse = PostApiMarketdataInstrumentsResponses[keyof PostApiMarketdataInstrumentsResponses];

export type GetApiMarketdataInstrumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/marketdata/instruments/{id}';
};

export type GetApiMarketdataInstrumentsByIdResponses = {
    /**
     * OK
     */
    200: InstrumentDetailsResponse;
};

export type GetApiMarketdataInstrumentsByIdResponse = GetApiMarketdataInstrumentsByIdResponses[keyof GetApiMarketdataInstrumentsByIdResponses];

export type PostApiMarketdataSyncTriggerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketdata/sync/trigger';
};

export type PostApiMarketdataSyncTriggerResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiMarketdataSyncTriggerResponse = PostApiMarketdataSyncTriggerResponses[keyof PostApiMarketdataSyncTriggerResponses];

export type GetApiMarketdataSyncStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/marketdata/sync/status';
};

export type GetApiMarketdataSyncStatusResponses = {
    /**
     * OK
     */
    200: SyncStatusResponse;
};

export type GetApiMarketdataSyncStatusResponse = GetApiMarketdataSyncStatusResponses[keyof GetApiMarketdataSyncStatusResponses];

export type GetApiMarketdataBondSeriesData = {
    body?: never;
    path?: never;
    query?: {
        onSaleOn?: string;
    };
    url: '/api/marketdata/bond-series';
};

export type GetApiMarketdataBondSeriesResponses = {
    /**
     * OK
     */
    200: Array<BondSeriesListItem>;
};

export type GetApiMarketdataBondSeriesResponse = GetApiMarketdataBondSeriesResponses[keyof GetApiMarketdataBondSeriesResponses];

export type GetApiMarketdataBondSeriesByCodeData = {
    body?: never;
    path: {
        code: string;
    };
    query?: never;
    url: '/api/marketdata/bond-series/{code}';
};

export type GetApiMarketdataBondSeriesByCodeResponses = {
    /**
     * OK
     */
    200: BondSeriesResponse;
};

export type GetApiMarketdataBondSeriesByCodeResponse = GetApiMarketdataBondSeriesByCodeResponses[keyof GetApiMarketdataBondSeriesByCodeResponses];
