<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>778d9a52-eb07-4397-b80d-70907ad0363f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\services\Identity\Skarbiec.Identity\Skarbiec.Identity.csproj" />
    <ProjectReference Include="..\services\Portfolio\Skarbiec.Portfolio\Skarbiec.Portfolio.csproj" />
    <ProjectReference Include="..\services\MarketData\Skarbiec.MarketData\Skarbiec.MarketData.csproj" />
    <ProjectReference Include="..\services\Strategy\Skarbiec.Strategy\Skarbiec.Strategy.csproj" />
    <ProjectReference Include="..\services\Reporting\Skarbiec.Reporting\Skarbiec.Reporting.csproj" />
  </ItemGroup>

</Project>
