// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Options } from './client/index.js';

export const getApiPortfolioMe = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/api/portfolio/me', ...options });

export const getApiPortfolioBondsById = <ThrowOnError extends boolean = false>(options: Options<unknown, ThrowOnError>) => (options.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/api/portfolio/bonds/{id}', ...options });
