// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddAssetRequest = {
    assetClass: AssetClass;
    name: string;
    currency?: string;
    instrumentId?: null | string;
    manualValue?: null | number | string;
    manualValueDate?: null | string;
    initialTransaction?: null | RecordTransactionRequest;
};

export type AddBondRequest = {
    name: string;
    seriesCode: string;
    type: TreasuryBondType;
    purchaseDate: string;
    bondCount: number | string;
    purchasePricePerBond: number | string;
    firstPeriodRatePercent: number | string;
    marginPercent?: null | number | string;
    earlyRedemptionFeePerBond: number | string;
    taxExempt?: boolean;
    fundingAssetId?: null | string;
};

export type AddDepositRequest = {
    name: string;
    bankName?: null | string;
    currency: string;
    principal: number | string;
    startDate: string;
    termLength: number | string;
    termUnit: DepositTermUnit;
    annualInterestRatePercent: number | string;
    capitalization: DepositCapitalization;
    taxExempt?: boolean;
    earlyBreakInterestLossPercent?: number | string;
    fundingAssetId?: null | string;
};

export type AddSavingsAccountRequest = {
    name: string;
    bankName?: null | string;
    currency: string;
    annualInterestRatePercent: number | string;
    taxExempt?: boolean;
    openingDeposit?: null | OpeningDepositRequest;
};

export type AssetClass = number;

export type AssetResponse = {
    id: string;
    portfolioId: string;
    assetClass: AssetClass;
    valuationMode: AssetValuationMode;
    name: string;
    currency: string;
    quantity: number | string;
    manualValue?: null | number | string;
    manualValueDate?: null | string;
    instrumentId?: null | string;
    transactionCount: number | string;
    depositMaturityDate?: null | string;
    depositSettled?: null | boolean;
    savingsInterestDue?: null | boolean;
    isArchived: boolean;
};

export type AssetValuationMode = number;

export type BondInterestPreviewResponse = {
    rows: Array<BondInterestPreviewRow>;
    totals: BondInterestPreviewTotals;
};

export type BondInterestPreviewRow = {
    periodIndex: number | string;
    start: string;
    end: string;
    ratePercent: number | string;
    bondCount: number | string;
    gross: number | string;
    tax: number | string;
    net: number | string;
};

export type BondInterestPreviewTotals = {
    gross: number | string;
    tax: number | string;
    net: number | string;
};

export type BondPeriodResponse = {
    index: number | string;
    start: string;
    end: string;
    state: BondPeriodState;
    settlement?: null | BondSettlementResponse;
};

export type BondPeriodState = number;

export type BondRedemptionKind = number;

export type BondRedemptionPreviewResponse = {
    date: string;
    bondCount: number | string;
    capitalisedInterest: number | string;
    discountIncome: number | string;
    taxableIncome: number | string;
    tax: number | string;
    proceeds: number | string;
};

export type BondRedemptionResponse = {
    kind: BondRedemptionKind;
    date: string;
    bondCount: number | string;
    tax: number | string;
    proceeds: number | string;
    destinationAssetName?: null | string;
    swapTargetAssetName?: null | string;
};

export type BondResponse = {
    assetId: string;
    portfolioId: string;
    portfolioName: string;
    portfolioIsArchived: boolean;
    isArchived: boolean;
    name: string;
    seriesCode: string;
    type: TreasuryBondType;
    purchaseDate: string;
    bondCount: number | string;
    purchasePricePerBond: number | string;
    firstPeriodRatePercent: number | string;
    marginPercent?: null | number | string;
    earlyRedemptionFeePerBond: number | string;
    taxExempt: boolean;
    maturityDate: string;
    nominalValue: number | string;
    bookValue: number | string;
    fundingAssetId?: null | string;
    fundingAssetName?: null | string;
    status: BondStatus;
    duePeriodCount: number | string;
    lastSettlement?: null | BondSettlementResponse;
    periods: Array<BondPeriodResponse>;
    redemptions: Array<BondRedemptionResponse>;
    swappedFrom?: null | BondSwapSourceResponse;
};

export type BondSettlementResponse = {
    settlementId: string;
    ratePercent: number | string;
    bondCount: number | string;
    grossInterest: number | string;
    tax: number | string;
};

export type BondStatus = number;

export type BondSwapSourceResponse = {
    assetId: string;
    name: string;
};

export type CreatePortfolioRequest = {
    name: string;
    description?: null | string;
    currency?: string;
};

export type CreateTransferRequest = {
    sourceAssetId: string;
    targetAssetId: string;
    amount: number | string;
    date: string;
};

export type CreateTransferResponse = {
    transferId: string;
};

export type DepositCapitalization = number;

export type DepositProjectionResponse = {
    grossInterest: number | string;
    tax: number | string;
    netInterest: number | string;
    finalAmount: number | string;
    netProfitPercent: number | string;
};

export type DepositResponse = {
    assetId: string;
    portfolioId: string;
    portfolioName: string;
    portfolioIsArchived: boolean;
    isArchived: boolean;
    name: string;
    bankName?: null | string;
    currency: string;
    principal: number | string;
    startDate: string;
    termLength: number | string;
    termUnit: DepositTermUnit;
    maturityDate: string;
    annualInterestRatePercent: number | string;
    capitalization: DepositCapitalization;
    taxExempt: boolean;
    earlyBreakInterestLossPercent: number | string;
    projection: DepositProjectionResponse;
    status: DepositStatus;
    settledOn?: null | string;
    settledGrossInterest?: null | number | string;
    settledTax?: null | number | string;
    fundingAssetId?: null | string;
    fundingAssetName?: null | string;
    paidOutOn?: null | string;
    paidOutToAssetName?: null | string;
    rolloverCount: number | string;
};

export type DepositSettlementPreviewResponse = {
    settledOn: string;
    grossInterest: number | string;
    tax: number | string;
    netInterest: number | string;
    finalAmount: number | string;
};

export type DepositStatus = number;

export type DepositTermUnit = number;

export type OpeningDepositRequest = {
    amount: number | string;
    date: string;
};

export type PagedResponseOfTransactionResponse = {
    items: Array<TransactionResponse>;
    page: number | string;
    pageSize: number | string;
    totalCount: number | string;
};

export type PayOutDepositRequest = {
    destinationAssetId: string;
    date: string;
};

export type PortfolioResponse = {
    id: string;
    name: string;
    description?: null | string;
    currency: string;
    isArchived: boolean;
    assetCount: number | string;
};

export type RecordTransactionRequest = {
    type: TransactionType;
    quantity?: number | string;
    unitPrice: number | string;
    date: string;
};

export type RedeemBondRequest = {
    destinationAssetId: string;
};

export type RollOverDepositRequest = {
    annualInterestRatePercent: number | string;
    grossInterest?: null | number | string;
    tax?: null | number | string;
};

export type SavingsAccountResponse = {
    assetId: string;
    portfolioId: string;
    portfolioName: string;
    portfolioIsArchived: boolean;
    isArchived: boolean;
    name: string;
    bankName?: null | string;
    currency: string;
    balance: number | string;
    annualInterestRatePercent: number | string;
    taxExempt: boolean;
    interestDue: boolean;
    duePeriodCount: number | string;
    lastSettlement?: null | SavingsInterestSettlementResponse;
};

export type SavingsInterestPreviewResponse = {
    periodStart: string;
    periodEnd: string;
    annualInterestRatePercent: number | string;
    averageDailyBalance: number | string;
    grossInterest: number | string;
    tax: number | string;
    netInterest: number | string;
    duePeriodCount: number | string;
};

export type SavingsInterestSettlementResponse = {
    settlementId: string;
    periodStart: string;
    periodEnd: string;
    grossInterest: number | string;
    tax: number | string;
    netInterest: number | string;
};

export type SettleBondInterestRequest = {
    periods: Array<SettleBondPeriodRequest>;
    destinationAssetId?: null | string;
};

export type SettleBondPeriodRequest = {
    periodIndex: number | string;
    ratePercent?: null | number | string;
};

export type SettleDepositRequest = {
    settledOn: string;
    grossInterest: number | string;
    tax: number | string;
    destinationAssetId?: null | string;
};

export type SettleSavingsInterestRequest = {
    periodEnd: string;
    grossInterest: number | string;
    tax: number | string;
};

export type SwapBondRequest = {
    bondCount: number | string;
    newBond: SwapNewBondRequest;
    destinationAssetId?: null | string;
};

export type SwapNewBondRequest = {
    name: string;
    seriesCode: string;
    type: TreasuryBondType;
    swapPricePerBond: number | string;
    firstPeriodRatePercent: number | string;
    marginPercent?: null | number | string;
    earlyRedemptionFeePerBond: number | string;
};

export type TransactionResponse = {
    id: string;
    assetId: string;
    type: TransactionType;
    quantity: number | string;
    unitPrice: number | string;
    currency: string;
    valuePln?: null | number | string;
    date: string;
    transfer?: null | TransactionTransferResponse;
    savingsInterestPeriodEnd?: null | string;
    bondInterestPeriodIndex?: null | number | string;
};

export type TransactionTransferResponse = {
    transferId: string;
    manual: boolean;
    counterpartAssetId: string;
    counterpartAssetName: string;
    counterpartPortfolioId: string;
    counterpartPortfolioName: string;
    direction: TransferDirection;
};

export type TransactionType = number;

export type TransferCandidateResponse = {
    assetId: string;
    name: string;
    portfolioId: string;
    portfolioName: string;
    balance: number | string;
};

export type TransferDirection = number;

export type TreasuryBondType = number;

export type UpdateAssetRequest = {
    assetClass: AssetClass;
    name: string;
    currency: string;
    instrumentId?: null | string;
    manualValue?: null | number | string;
    manualValueDate?: null | string;
};

export type UpdateBondRequest = {
    name: string;
    seriesCode: string;
    type: TreasuryBondType;
    purchaseDate: string;
    bondCount: number | string;
    purchasePricePerBond: number | string;
    firstPeriodRatePercent: number | string;
    marginPercent?: null | number | string;
    earlyRedemptionFeePerBond: number | string;
    taxExempt?: boolean;
};

export type UpdateDepositRequest = {
    name: string;
    bankName?: null | string;
    principal: number | string;
    startDate: string;
    termLength: number | string;
    termUnit: DepositTermUnit;
    annualInterestRatePercent: number | string;
    capitalization: DepositCapitalization;
    taxExempt?: boolean;
    earlyBreakInterestLossPercent?: number | string;
};

export type UpdatePortfolioRequest = {
    name: string;
    description?: null | string;
    currency: string;
};

export type UpdateSavingsAccountRequest = {
    name: string;
    bankName?: null | string;
    annualInterestRatePercent: number | string;
    taxExempt?: boolean;
};

export type UpdateTransactionRequest = {
    type: TransactionType;
    quantity?: number | string;
    unitPrice: number | string;
    date: string;
};

export type GetApiPortfolioMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/me';
};

export type GetApiPortfolioMeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiPortfolioMeResponse = GetApiPortfolioMeResponses[keyof GetApiPortfolioMeResponses];

export type GetApiPortfolioPortfoliosData = {
    body?: never;
    path?: never;
    query?: {
        includeArchived?: boolean;
    };
    url: '/api/portfolio/portfolios';
};

export type GetApiPortfolioPortfoliosResponses = {
    /**
     * OK
     */
    200: Array<PortfolioResponse>;
};

export type GetApiPortfolioPortfoliosResponse = GetApiPortfolioPortfoliosResponses[keyof GetApiPortfolioPortfoliosResponses];

export type PostApiPortfolioPortfoliosData = {
    body: CreatePortfolioRequest;
    path?: never;
    query?: never;
    url: '/api/portfolio/portfolios';
};

export type PostApiPortfolioPortfoliosResponses = {
    /**
     * Created
     */
    201: PortfolioResponse;
};

export type PostApiPortfolioPortfoliosResponse = PostApiPortfolioPortfoliosResponses[keyof PostApiPortfolioPortfoliosResponses];

export type DeleteApiPortfolioPortfoliosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type DeleteApiPortfolioPortfoliosByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByIdResponse = DeleteApiPortfolioPortfoliosByIdResponses[keyof DeleteApiPortfolioPortfoliosByIdResponses];

export type GetApiPortfolioPortfoliosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type GetApiPortfolioPortfoliosByIdResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type GetApiPortfolioPortfoliosByIdResponse = GetApiPortfolioPortfoliosByIdResponses[keyof GetApiPortfolioPortfoliosByIdResponses];

export type PutApiPortfolioPortfoliosByIdData = {
    body: UpdatePortfolioRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type PutApiPortfolioPortfoliosByIdResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type PutApiPortfolioPortfoliosByIdResponse = PutApiPortfolioPortfoliosByIdResponses[keyof PutApiPortfolioPortfoliosByIdResponses];

export type PostApiPortfolioPortfoliosByIdArchiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}/archive';
};

export type PostApiPortfolioPortfoliosByIdArchiveResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type PostApiPortfolioPortfoliosByIdArchiveResponse = PostApiPortfolioPortfoliosByIdArchiveResponses[keyof PostApiPortfolioPortfoliosByIdArchiveResponses];

export type PostApiPortfolioPortfoliosByIdRestoreData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}/restore';
};

export type PostApiPortfolioPortfoliosByIdRestoreResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type PostApiPortfolioPortfoliosByIdRestoreResponse = PostApiPortfolioPortfoliosByIdRestoreResponses[keyof PostApiPortfolioPortfoliosByIdRestoreResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsData = {
    body?: never;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponse>;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsData = {
    body: AddAssetRequest;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses = {
    /**
     * Created
     */
    201: AssetResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body: UpdateAssetRequest;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdArchiveData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}/archive';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdArchiveResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdArchiveResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdArchiveResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdArchiveResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdRestoreData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}/restore';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdRestoreResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdRestoreResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdRestoreResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsByIdRestoreResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTransactionResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsData = {
    body: RecordTransactionRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses = {
    /**
     * Created
     */
    201: TransactionResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions/{id}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdData = {
    body: UpdateTransactionRequest;
    path: {
        portfolioId: string;
        assetId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions/{id}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses = {
    /**
     * OK
     */
    200: TransactionResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponse = PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsData = {
    body: AddDepositRequest;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits';
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsResponses = {
    /**
     * Created
     */
    201: DepositResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsResponse = PostApiPortfolioPortfoliosByPortfolioIdDepositsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdDepositsResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}';
};

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses = {
    /**
     * OK
     */
    200: DepositResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponse = GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdData = {
    body: UpdateDepositRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses = {
    /**
     * OK
     */
    200: DepositResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponse = PutApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdResponses];

export type GetApiPortfolioDepositsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/deposits';
};

export type GetApiPortfolioDepositsResponses = {
    /**
     * OK
     */
    200: Array<DepositResponse>;
};

export type GetApiPortfolioDepositsResponse = GetApiPortfolioDepositsResponses[keyof GetApiPortfolioDepositsResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettlementPreviewData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}/settlement-preview';
};

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettlementPreviewResponses = {
    /**
     * OK
     */
    200: DepositSettlementPreviewResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettlementPreviewResponse = GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettlementPreviewResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettlementPreviewResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettleData = {
    body: SettleDepositRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}/settle';
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettleResponses = {
    /**
     * OK
     */
    200: DepositResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettleResponse = PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettleResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdSettleResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdPayoutData = {
    body: PayOutDepositRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}/payout';
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdPayoutResponses = {
    /**
     * OK
     */
    200: DepositResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdPayoutResponse = PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdPayoutResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdPayoutResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdRolloverData = {
    body: RollOverDepositRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/deposits/{assetId}/rollover';
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdRolloverResponses = {
    /**
     * OK
     */
    200: DepositResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdRolloverResponse = PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdRolloverResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdDepositsByAssetIdRolloverResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdBondsData = {
    body: AddBondRequest;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds';
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsResponses = {
    /**
     * Created
     */
    201: BondResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsResponse = PostApiPortfolioPortfoliosByPortfolioIdBondsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdBondsResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}';
};

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses = {
    /**
     * OK
     */
    200: BondResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponse = GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdData = {
    body: UpdateBondRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses = {
    /**
     * OK
     */
    200: BondResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponse = PutApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdResponses];

export type GetApiPortfolioBondsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/bonds';
};

export type GetApiPortfolioBondsResponses = {
    /**
     * OK
     */
    200: Array<BondResponse>;
};

export type GetApiPortfolioBondsResponse = GetApiPortfolioBondsResponses[keyof GetApiPortfolioBondsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsData = {
    body: SettleBondInterestRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/interest-settlements';
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsResponses = {
    /**
     * Created
     */
    201: Array<BondSettlementResponse>;
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsResponse = PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsPreviewData = {
    body: SettleBondInterestRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/interest-settlements/preview';
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsPreviewResponses = {
    /**
     * OK
     */
    200: BondInterestPreviewResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsPreviewResponse = PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsPreviewResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsPreviewResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsBySettlementIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
        settlementId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/interest-settlements/{settlementId}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsBySettlementIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsBySettlementIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsBySettlementIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdInterestSettlementsBySettlementIdResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionData = {
    body: RedeemBondRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/redemption';
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionResponses = {
    /**
     * OK
     */
    200: BondResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionResponse = PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionPreviewData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/redemption-preview';
};

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionPreviewResponses = {
    /**
     * OK
     */
    200: BondRedemptionPreviewResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionPreviewResponse = GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionPreviewResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdRedemptionPreviewResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdSwapData = {
    body: SwapBondRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/bonds/{assetId}/swap';
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdSwapResponses = {
    /**
     * Created
     */
    201: BondResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdSwapResponse = PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdSwapResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdBondsByAssetIdSwapResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsData = {
    body: AddSavingsAccountRequest;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts';
};

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsResponses = {
    /**
     * Created
     */
    201: SavingsAccountResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsResponse = PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts/{assetId}';
};

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses = {
    /**
     * OK
     */
    200: SavingsAccountResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponse = GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdData = {
    body: UpdateSavingsAccountRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts/{assetId}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses = {
    /**
     * OK
     */
    200: SavingsAccountResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponse = PutApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdResponses];

export type GetApiPortfolioSavingsAccountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/savings-accounts';
};

export type GetApiPortfolioSavingsAccountsResponses = {
    /**
     * OK
     */
    200: Array<SavingsAccountResponse>;
};

export type GetApiPortfolioSavingsAccountsResponse = GetApiPortfolioSavingsAccountsResponses[keyof GetApiPortfolioSavingsAccountsResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestPreviewData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts/{assetId}/interest-preview';
};

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestPreviewResponses = {
    /**
     * OK
     */
    200: SavingsInterestPreviewResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestPreviewResponse = GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestPreviewResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestPreviewResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsData = {
    body: SettleSavingsInterestRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts/{assetId}/interest-settlements';
};

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsResponses = {
    /**
     * Created
     */
    201: SavingsInterestSettlementResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsResponse = PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsBySettlementIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
        settlementId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/savings-accounts/{assetId}/interest-settlements/{settlementId}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsBySettlementIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsBySettlementIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsBySettlementIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdSavingsAccountsByAssetIdInterestSettlementsBySettlementIdResponses];

export type GetApiPortfolioTransferCandidatesData = {
    body?: never;
    path?: never;
    query: {
        currency: string;
        assetClass: AssetClass;
    };
    url: '/api/portfolio/transfer-candidates';
};

export type GetApiPortfolioTransferCandidatesResponses = {
    /**
     * OK
     */
    200: Array<TransferCandidateResponse>;
};

export type GetApiPortfolioTransferCandidatesResponse = GetApiPortfolioTransferCandidatesResponses[keyof GetApiPortfolioTransferCandidatesResponses];

export type PostApiPortfolioTransfersData = {
    body: CreateTransferRequest;
    path?: never;
    query?: never;
    url: '/api/portfolio/transfers';
};

export type PostApiPortfolioTransfersResponses = {
    /**
     * Created
     */
    201: CreateTransferResponse;
};

export type PostApiPortfolioTransfersResponse = PostApiPortfolioTransfersResponses[keyof PostApiPortfolioTransfersResponses];

export type DeleteApiPortfolioTransfersByTransferIdData = {
    body?: never;
    path: {
        transferId: string;
    };
    query?: never;
    url: '/api/portfolio/transfers/{transferId}';
};

export type DeleteApiPortfolioTransfersByTransferIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioTransfersByTransferIdResponse = DeleteApiPortfolioTransfersByTransferIdResponses[keyof DeleteApiPortfolioTransfersByTransferIdResponses];
