// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:60585/' | (string & {});
};

export type AddAssetRequest = {
    assetClass: AssetClass;
    name: string;
    currency?: string;
    quantity?: number | string;
    manualValue: number | string;
    manualValueDate: string;
};

export type AssetClass = number;

export type AssetResponse = {
    id: string;
    portfolioId: string;
    assetClass: AssetClass;
    name: string;
    currency: string;
    quantity: number | string;
    manualValue: number | string;
    manualValueDate: string;
    instrumentId?: null | string;
};

export type CreatePortfolioRequest = {
    name: string;
    description?: null | string;
    currency?: string;
};

export type PagedResponseOfTransactionResponse = {
    items: Array<TransactionResponse>;
    page: number | string;
    pageSize: number | string;
    totalCount: number | string;
};

export type PortfolioResponse = {
    id: string;
    name: string;
    description?: null | string;
    currency: string;
    isArchived: boolean;
};

export type RecordTransactionRequest = {
    type: TransactionType;
    quantity?: number | string;
    unitPrice: number | string;
    fee?: number | string;
    date: string;
};

export type TransactionResponse = {
    id: string;
    assetId: string;
    type: TransactionType;
    quantity: number | string;
    unitPrice: number | string;
    fee: number | string;
    date: string;
};

export type TransactionType = number;

export type UpdateAssetRequest = {
    assetClass: AssetClass;
    name: string;
    currency: string;
    quantity?: number | string;
    manualValue: number | string;
    manualValueDate: string;
};

export type UpdatePortfolioRequest = {
    name: string;
    description?: null | string;
    currency: string;
};

export type UpdateTransactionRequest = {
    type: TransactionType;
    quantity?: number | string;
    unitPrice: number | string;
    fee?: number | string;
    date: string;
};

export type GetApiPortfolioMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/portfolio/me';
};

export type GetApiPortfolioMeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiPortfolioMeResponse = GetApiPortfolioMeResponses[keyof GetApiPortfolioMeResponses];

export type GetApiPortfolioPortfoliosData = {
    body?: never;
    path?: never;
    query?: {
        includeArchived?: boolean;
    };
    url: '/api/portfolio/portfolios';
};

export type GetApiPortfolioPortfoliosResponses = {
    /**
     * OK
     */
    200: Array<PortfolioResponse>;
};

export type GetApiPortfolioPortfoliosResponse = GetApiPortfolioPortfoliosResponses[keyof GetApiPortfolioPortfoliosResponses];

export type PostApiPortfolioPortfoliosData = {
    body: CreatePortfolioRequest;
    path?: never;
    query?: never;
    url: '/api/portfolio/portfolios';
};

export type PostApiPortfolioPortfoliosResponses = {
    /**
     * Created
     */
    201: PortfolioResponse;
};

export type PostApiPortfolioPortfoliosResponse = PostApiPortfolioPortfoliosResponses[keyof PostApiPortfolioPortfoliosResponses];

export type DeleteApiPortfolioPortfoliosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type DeleteApiPortfolioPortfoliosByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByIdResponse = DeleteApiPortfolioPortfoliosByIdResponses[keyof DeleteApiPortfolioPortfoliosByIdResponses];

export type GetApiPortfolioPortfoliosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type GetApiPortfolioPortfoliosByIdResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type GetApiPortfolioPortfoliosByIdResponse = GetApiPortfolioPortfoliosByIdResponses[keyof GetApiPortfolioPortfoliosByIdResponses];

export type PutApiPortfolioPortfoliosByIdData = {
    body: UpdatePortfolioRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}';
};

export type PutApiPortfolioPortfoliosByIdResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type PutApiPortfolioPortfoliosByIdResponse = PutApiPortfolioPortfoliosByIdResponses[keyof PutApiPortfolioPortfoliosByIdResponses];

export type PostApiPortfolioPortfoliosByIdArchiveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{id}/archive';
};

export type PostApiPortfolioPortfoliosByIdArchiveResponses = {
    /**
     * OK
     */
    200: PortfolioResponse;
};

export type PostApiPortfolioPortfoliosByIdArchiveResponse = PostApiPortfolioPortfoliosByIdArchiveResponses[keyof PostApiPortfolioPortfoliosByIdArchiveResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsData = {
    body?: never;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetResponse>;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsData = {
    body: AddAssetRequest;
    path: {
        portfolioId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses = {
    /**
     * Created
     */
    201: AssetResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdData = {
    body: UpdateAssetRequest;
    path: {
        portfolioId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{id}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses = {
    /**
     * OK
     */
    200: AssetResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponse = PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdAssetsByIdResponses];

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: {
        page?: number | string;
        pageSize?: number | string;
    };
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions';
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses = {
    /**
     * OK
     */
    200: PagedResponseOfTransactionResponse;
};

export type GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponse = GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses[keyof GetApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses];

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsData = {
    body: RecordTransactionRequest;
    path: {
        portfolioId: string;
        assetId: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions';
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses = {
    /**
     * Created
     */
    201: TransactionResponse;
};

export type PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponse = PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses[keyof PostApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsResponses];

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdData = {
    body?: never;
    path: {
        portfolioId: string;
        assetId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions/{id}';
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponse = DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses[keyof DeleteApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses];

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdData = {
    body: UpdateTransactionRequest;
    path: {
        portfolioId: string;
        assetId: string;
        id: string;
    };
    query?: never;
    url: '/api/portfolio/portfolios/{portfolioId}/assets/{assetId}/transactions/{id}';
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses = {
    /**
     * OK
     */
    200: TransactionResponse;
};

export type PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponse = PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses[keyof PutApiPortfolioPortfoliosByPortfolioIdAssetsByAssetIdTransactionsByIdResponses];
